version: '3'

networks:
  coolshop:
    driver: bridge

services:
  api:
    container_name: api
    image: "mcr.microsoft.com/dotnet/sdk:6.0"
    depends_on:
      - db
    volumes:
      - ./Coolshop_api/API_ShopingClose/:/app
    command: dotnet watch --project ./app run --urls "http://0.0.0.0:80"
    networks:
      - coolshop
    ports:
      - 5191:80

  db:
    restart: always
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234@qwerA
      MYSQL_DATABASE: mysql_server
    ports:
      - 3306:3306
    volumes:
      - ./db.sql:/db.sql
      - ./DB_DATA:/var/lib/mysql
    networks:
      - coolshop

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./front-end/client:/srv/www/client
      - ./front-end/admin:/srv/www/admin
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - coolshop
    depends_on:
      - db
      - api
