version: '3'

networks:
  coolshop:
    driver: bridge

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/srv/www/client
      - ./admin:/srv/www/admin
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - coolshop
